#!/bin/bash
#
# Author: 	Jong Park
# Filename: testall
# Description: This script takes the four Unit-tests and four card-tests and runs gcov and saves to unittestresults.out

echo -e "\033[0;32m Testing unittests...\033[0m"

./unittest1
gcov unittest1 >> unittestresults.out
./unittest2
gcov unittest2 >> unittestresults.out
./unittest3
gcov unittest3 >> unittestresults.out
./unittest4
gcov unittest4 >> unittestresults.out

echo
echo
echo -e "\033[0;32m Testing cardtests...\033[0m"

./cardtest1
gcov cardtest1 >> unittestresults.out
./cardtest2
gcov cardtest2 >> unittestresults.out
./cardtest3
gcov cardtest3 >> unittestresults.out
./cardtest4
gcov cardtest4 >> unittestresults.out

echo
echo
echo -e "\033[0;32m Testing cardtests...\033[0m"

./randomtestcard1
gcov randomtestcard1 >> randomtestcard1.out
./randomtestcard2
gcov randomtestcard2 >> randomtestcard2.out
./randomtestcard3
gcov randomtestcard3 >> randomtestcard3.out
